// <auto-generated />
using System;
using Marketplace.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Marketplace.Infrastructure.Migrations
{
    [DbContext(typeof(MarketplaceDbContext))]
    [Migration("20260819054009_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Marketplace.Domain.BoostPackages.BoostPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("PriceAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("price_amount");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("priority_level");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tier");

                    b.HasKey("Id")
                        .HasName("pk_boost_packages");

                    b.ToTable("boost_packages", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Boosts.Boost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("activated_at");

                    b.Property<Guid?>("ActivatedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("activated_by_admin_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text")
                        .HasColumnName("payment_reference");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("priority_level");

                    b.Property<DateTime>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_boosts");

                    b.HasIndex("ActivatedByAdminId")
                        .HasDatabaseName("ix_boosts_activated_by_admin_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_boosts_expires_at");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_boosts_listing_id");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_boosts_package_id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_boosts_seller_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_boosts_status");

                    b.ToTable("boosts", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("LabelEn")
                        .HasColumnType("text")
                        .HasColumnName("label_en");

                    b.Property<string>("LabelVi")
                        .HasColumnType("text")
                        .HasColumnName("label_vi");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Identities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text")
                        .HasColumnName("google_id");

                    b.Property<string>("LocationProvince")
                        .HasColumnType("text")
                        .HasColumnName("location_province");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_id");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Inquiries.Inquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BuyerEmail")
                        .HasColumnType("text")
                        .HasColumnName("buyer_email");

                    b.Property<string>("BuyerName")
                        .HasColumnType("text")
                        .HasColumnName("buyer_name");

                    b.Property<string>("BuyerPhone")
                        .HasColumnType("text")
                        .HasColumnName("buyer_phone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inquiries");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_inquiries_listing_id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_inquiries_seller_id");

                    b.ToTable("inquiries", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Listings.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("VND")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("LocationProvince")
                        .HasColumnType("text")
                        .HasColumnName("location_province");

                    b.Property<long?>("PriceAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("price_amount");

                    b.Property<bool>("PriceContact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("price_contact");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("published_at");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "simple")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Title", "Description" });

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubcategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("subcategory_id");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.HasKey("Id")
                        .HasName("pk_listings");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_listings_category_id");

                    b.HasIndex("LocationProvince")
                        .HasDatabaseName("ix_listings_location_province");

                    b.HasIndex("PriceAmount")
                        .HasDatabaseName("ix_listings_price_amount");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_listings_published_at");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_listings_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_listings_seller_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_listings_slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_listings_status");

                    b.HasIndex("SubcategoryId")
                        .HasDatabaseName("ix_listings_subcategory_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_listings_title");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.ToTable("listings", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Listings.ListingPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_listing_photos");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_listing_photos_listing_id");

                    b.ToTable("listing_photos", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.ModerationDecisions.ModerationDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("decision");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_moderation_decisions");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("ix_moderation_decisions_admin_id");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_moderation_decisions_listing_id");

                    b.ToTable("moderation_decisions", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Reports.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reason");

                    b.Property<string>("ReporterContact")
                        .HasColumnType("text")
                        .HasColumnName("reporter_contact");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_admin_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_reports_listing_id");

                    b.HasIndex("ResolvedByAdminId")
                        .HasDatabaseName("ix_reports_resolved_by_admin_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_reports_status");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Boosts.Boost", b =>
                {
                    b.HasOne("Marketplace.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("ActivatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_boosts_users_activated_by_admin_id");

                    b.HasOne("Marketplace.Domain.Listings.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_boosts_listings_listing_id");

                    b.HasOne("Marketplace.Domain.BoostPackages.BoostPackage", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boosts_boost_packages_package_id");

                    b.HasOne("Marketplace.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_boosts_users_seller_id");
                });

            modelBuilder.Entity("Marketplace.Domain.Categories.Category", b =>
                {
                    b.HasOne("Marketplace.Domain.Categories.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Marketplace.Domain.Inquiries.Inquiry", b =>
                {
                    b.HasOne("Marketplace.Domain.Listings.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inquiries_listings_listing_id");

                    b.HasOne("Marketplace.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inquiries_users_seller_id");
                });

            modelBuilder.Entity("Marketplace.Domain.Listings.Listing", b =>
                {
                    b.HasOne("Marketplace.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_listings_categories_category_id");

                    b.HasOne("Marketplace.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_listings_users_seller_id");

                    b.HasOne("Marketplace.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_listings_categories_subcategory_id");

                    b.OwnsOne("Marketplace.Domain.Listings.ListingSpecs", "Specs", b1 =>
                        {
                            b1.Property<Guid>("ListingId")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Brand");

                            b1.Property<string>("Capacity");

                            b1.Property<int?>("Hours");

                            b1.Property<string>("Model");

                            b1.Property<string>("Origin");

                            b1.Property<int?>("Year");

                            b1.HasKey("ListingId");

                            b1.ToTable("listings");

                            b1
                                .ToJson("specs")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ListingId")
                                .HasConstraintName("fk_listings_listings_id");
                        });

                    b.Navigation("Specs");
                });

            modelBuilder.Entity("Marketplace.Domain.Listings.ListingPhoto", b =>
                {
                    b.HasOne("Marketplace.Domain.Listings.Listing", null)
                        .WithMany("Photos")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listing_photos_listings_listing_id");
                });

            modelBuilder.Entity("Marketplace.Domain.ModerationDecisions.ModerationDecision", b =>
                {
                    b.HasOne("Marketplace.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_moderation_decisions_users_admin_id");

                    b.HasOne("Marketplace.Domain.Listings.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_moderation_decisions_listings_listing_id");
                });

            modelBuilder.Entity("Marketplace.Domain.Reports.Report", b =>
                {
                    b.HasOne("Marketplace.Domain.Listings.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reports_listings_listing_id");

                    b.HasOne("Marketplace.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("ResolvedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reports_users_resolved_by_admin_id");
                });

            modelBuilder.Entity("Marketplace.Domain.Categories.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Marketplace.Domain.Listings.Listing", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
