using NpgsqlTypes;

namespace Marketplace.Domain.Listings;

/// <summary>The core aggregate — a machine/part/equipment offered for sale.</summary>
public class Listing : Entity<Guid>, IAggregateRoot
{
    public Guid SellerId { get; private set; }

    public Guid CategoryId { get; private set; }

    public Guid? SubcategoryId { get; private set; }

    public string Title { get; private set; }

    public string Slug { get; private set; }

    public Condition Condition { get; private set; }

    public long? PriceAmount { get; private set; }

    public bool PriceContact { get; private set; }

    public string Currency { get; private set; } = "VND";

    public string LocationProvince { get; private set; }

    public string Description { get; private set; }

    public ListingSpecs Specs { get; private set; } = new();

    public ListingStatus Status { get; private set; } = ListingStatus.PENDING;

    public int ViewCount { get; private set; }

    /// <summary>Full-text search vector generated by Postgres from Title + Description.</summary>
    public NpgsqlTsVector SearchVector { get; private set; }

    public DateTime? PublishedAt { get; private set; }

    public DateTime? ExpiresAt { get; private set; }

    public DateTime CreatedAt { get; private set; }

    public DateTime UpdatedAt { get; private set; }

    public ICollection<ListingPhoto> Photos { get; private set; } = new List<ListingPhoto>();

    /// <summary>Records a buyer view of this listing (write side; persisted via the unit of work).</summary>
    public void RegisterView() => ViewCount++;
}
